#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App8.Resource", IsApplication=true)]

namespace App8
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgroundMenu = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int clubs = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int diamonds = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int hearts = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int mask1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int mask2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int spades = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int balance = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int bet = 2131034129;
			
			// aapt resource value: 0x7f050006
			public const int button1 = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int buttonChaked = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int buttonContinue = 2131034124;
			
			// aapt resource value: 0x7f05000e
			public const int buttonDoubleBet = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int buttonGetCard = 2131034123;
			
			// aapt resource value: 0x7f050007
			public const int buttonLang = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int buttonSetBet = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int buttonShowCard = 2131034125;
			
			// aapt resource value: 0x7f05001a
			public const int carddiller1 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int carddiller2 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int carddiller3 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int carddiller4 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int carddiller5 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int carddiller6 = 2131034143;
			
			// aapt resource value: 0x7f050014
			public const int cardplayer1 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int cardplayer2 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int cardplayer3 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int cardplayer4 = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int cardplayer5 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int cardplayer6 = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int dillerCoins = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int editText1 = 2131034121;
			
			// aapt resource value: 0x7f050010
			public const int info = 2131034128;
			
			// aapt resource value: 0x7f050008
			public const int numberPicker1 = 2131034120;
			
			// aapt resource value: 0x7f05000f
			public const int playerCoins = 2131034127;
			
			// aapt resource value: 0x7f050002
			public const int radioButton1 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int radioButton2 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int radioButton3 = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int radioGroup1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textViewLang = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChooseLanguage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int StartGame = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int EnBalance = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int EnBet = 2130968588;
			
			// aapt resource value: 0x7f040004
			public const int EnCancel = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int EnChooseLanguage = 2130968578;
			
			// aapt resource value: 0x7f04000a
			public const int EnContinue = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int EnDoubleBet = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int EnGetCard = 2130968584;
			
			// aapt resource value: 0x7f04000e
			public const int EnIncorrectBet = 2130968590;
			
			// aapt resource value: 0x7f040003
			public const int EnOk = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int EnSetBet = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int EnStand = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int EnStartGame = 2130968581;
			
			// aapt resource value: 0x7f04000d
			public const int EntextViewLang = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int RuBalance = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int RuBet = 2130968601;
			
			// aapt resource value: 0x7f040011
			public const int RuCancel = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int RuChooseLanguage = 2130968591;
			
			// aapt resource value: 0x7f040017
			public const int RuContinue = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int RuDoubleBet = 2130968598;
			
			// aapt resource value: 0x7f040015
			public const int RuGetCard = 2130968597;
			
			// aapt resource value: 0x7f04001b
			public const int RuIncorrectBet = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int RuOk = 2130968592;
			
			// aapt resource value: 0x7f040013
			public const int RuSetBet = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int RuStand = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int RuStartGame = 2130968594;
			
			// aapt resource value: 0x7f04001a
			public const int RutextViewLang = 2130968602;
			
			// aapt resource value: 0x7f040025
			public const int UkBalance = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int UkBet = 2130968614;
			
			// aapt resource value: 0x7f04001e
			public const int UkCancel = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int UkChooseLanguage = 2130968604;
			
			// aapt resource value: 0x7f040024
			public const int UkContinue = 2130968612;
			
			// aapt resource value: 0x7f040023
			public const int UkDoubleBet = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int UkGetCard = 2130968610;
			
			// aapt resource value: 0x7f040028
			public const int UkIncorrectBet = 2130968616;
			
			// aapt resource value: 0x7f04001d
			public const int UkOk = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int UkSetBet = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int UkStand = 2130968609;
			
			// aapt resource value: 0x7f04001f
			public const int UkStartGame = 2130968607;
			
			// aapt resource value: 0x7f040027
			public const int UktextViewLang = 2130968615;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
